export const booksConstants = {
    EDIT_SUCCESS: 'BOOK_EDIT_SUCCESS',
    EDIT_FAILURE: 'BOOK_EDIT_FAILURE',

    ADD_BOOK_SUCCESS: 'BOOK_ADD_SUCCESS',
    ADD_BOOK_FAILURE: 'BOOK_ADD_FAILURE',

    GET_BOOK_SUCCESS: 'BOOK_GET_SUCCESS',
    GET_BOOK_FAILURE: 'BOOK_GET_FAILURE',
    GET_BOOK_REQUEST: 'BOOK_GET_REQUEST',

    GET_BOOKS_SUCCESS: 'BOOK_GETS_SUCCESS',
    GET_BOOKS_FAILURE: 'BOOK_GETS_FAILURE',

    DELETE_BOOK_SUCCESS: 'BOOK_DELETE_SUCCESS',
    DELETE_BOOK_FAILURE: 'BOOK_DELETE_FAILURE',

    GET_GENRES_SUCCESS: 'GET_GENRES_SUCCESS',
    GET_GENRES_FAILURE: 'GET_GENRES_FAILURE',

    GET_PAGINATION_PAGES_NUMBER_SUCCESS: 'GET_PAGINATION_PAGES_NUMBER_SUCCESS',
    GET_PAGINATION_PAGES_NUMBER_FAILURE: 'GET_PAGINATION_PAGES_NUMBER_FAILURE',
    SAVE_CATEGORY: 'SAVE_CATEGORY',
    SAVE_PAGINATION_PAGE: 'SAVE_PAGINATION_PAGE'
};
