export const cartConstants = {
    ADD_TO_CART : 'ADD_TO_CART',

    CHECKOUT_REQUEST : 'CHECKOUT_REQUEST',
    CHECKOUT_SUCCESS : 'CHECKOUT_SUCCESS',
    CHECKOUT_FAILURE : 'CHECKOUT_FAILURE',

    RECEIVE_PRODUCTS : 'RECEIVE_PRODUCTS',

    CLEAR : 'CLEAR_BASKET',
    REMOVE_BOOK : 'REMOVE_BOOK'
};
